apiVersion: v1
data:
  API_KEY: c3VwZXJzZWNyZXRhcGlrZXk=
kind: Secret
metadata:
  name: hello-secret
type: Opaque
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      automountServiceAccountToken: false
      containers:
      - image: alpine:3.18.2
        name: hello-client
        command: ["sh", "-c"]
        args: ["while true; do wget -qO- --timeout=2 http://hello-server.team1.svc:8080; sleep 30; done"]
        securityContext:
          readOnlyRootFilesystem: true
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: hello-secret
              key: API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"     
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: not-hello
  name: hello-client-blocked
spec:
  replicas: 1
  selector:
    matchLabels:
      app: not-hello
  template:
    metadata:
      labels:
        app: not-hello
    spec:
      automountServiceAccountToken: false
      containers:
      - image: alpine:3.18.2
        name: hello-client-blocked
        command: ["sh", "-c"]
        args: ["while true; do wget -qO- --timeout=2 http://hello-server.team1.svc:8080; sleep 30; done"]
        securityContext:
          readOnlyRootFilesystem: true
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: hello-secret
              key: API_KEY           
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"