apiVersion: v1
kind: Namespace
metadata:
  name: security-playground-unprivileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-playground-unprivileged
  namespace: security-playground-unprivileged
  labels:
    app.kubernetes.io/name: security-playground-unprivileged
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: security-playground-unprivileged
  template:
    metadata:
      labels:
        app.kubernetes.io/name: security-playground-unprivileged
    spec:
      containers:
        - name: security-playground-unprivileged
          image: jasonumiker/security-playground:190523
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
---
apiVersion: v1
kind: Service
metadata:
  name: security-playground-unprivileged
  namespace: security-playground-unprivileged
  labels:
    app.kubernetes.io/name: security-playground-unprivileged
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      nodePort: 30285
  selector:
    app.kubernetes.io/name: security-playground-unprivileged