apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-playground-restricted
  namespace: security-playground-restricted
  labels:
    app.kubernetes.io/name: security-playground-restricted
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: security-playground-restricted
  template:
    metadata:
      labels:
        app.kubernetes.io/name: security-playground-restricted
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      hostPID: true
      containers:
        - name: security-playground-unprivileged
          image: public.ecr.aws/m9h2b5e7/security-playground-unprivileged:110623
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          securityContext:
            privileged: true
