apiVersion: v1
kind: Namespace
metadata:
  name: oracle-sakila
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracle-sakila-deployment
  labels:
    app: oracle-sakila
  namespace: oracle-sakila
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oracle-sakila
  template:
    metadata:
      labels:
        app: oracle-sakila
    spec:
      containers:
      - name: oracle-sakila
        image: jasonumiker/oracle-sakila:050623
        ports:
        - containerPort: 1521
        env:
        - name: ORACLE_PASSWORD
          value: "sakila"
        - name: APP_USER
          value: "sakila"
        - name: APP_USER_PASSWORD
          value: "sakila"