agent:
  prometheus:
    file: true
    yaml:
      global:
        scrape_interval: 10s
      scrape_configs:
      - job_name: k8s-pods
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - action: keep
          regex: __HOSTIPS__
          source_labels:
          - __meta_kubernetes_pod_host_ip
        - action: keep
          regex: true
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_scrape
        - action: replace
          regex: (https?)
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_scheme
          target_label: __scheme__
        - action: replace
          regex: (.+)
          source_labels:
          - __meta_kubernetes_pod_annotation_prometheus_io_path
          target_label: __metrics_path__
        - action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          source_labels:
          - __address__
          - __meta_kubernetes_pod_annotation_prometheus_io_port
          target_label: __address__
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_uid
          target_label: sysdig_k8s_pod_uid
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_container_name
          target_label: sysdig_k8s_pod_container_name
        sample_limit: 40000
        tls_config:
          insecure_skip_verify: true
  sysdig:
    settings:
      prometheus:
        enabled: true
      use_promscrape: true