apiVersion: apps/v1

kind: Deployment
metadata:
  name: dnsloadgen-deployment
  labels:
    app: dnsloadgen
spec:
  replicas: 50
  selector:
    matchLabels:
      app: dnsloadgen
  template:
    metadata:
      labels:
        app: dnsloadgen
    spec:
      containers:
      - name: dnsloadgen
        image: jasonumiker/dnsloadgen:latest