kind: Service
apiVersion: v1
metadata:
  labels:
    app: hello-server
  name: hello-server
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-server
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-server
  name: hello-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      automountServiceAccountToken: false
      containers:
      - image: public.ecr.aws/m9h2b5e7/hello-app:270723
        name: hello-server
        ports:
        - containerPort: 8080
          protocol: TCP
        securityContext:
          readOnlyRootFilesystem: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
